# This file is part of the research.fi service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

# Stage 1: Build Angular application
FROM node:12.12.0-alpine as angular
COPY . /app
WORKDIR /app
RUN npm install
RUN npm run build:ssr
EXPOSE 4000
CMD npm run serve:ssr