// This file is part of the research.fi service
//
// Copyright 2019 Ministry of Education and Culture, Finland
//
// :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
// :license: MIT
pipeline {
  agent {
    node {
      label 'nodejs' 
    }
  }

  environment {
    // Get short version of Git commit hash.
    GIT_COMMIT_SHORT = sh(
      script: "printf \$(git rev-parse --short ${GIT_COMMIT})",
      returnStdout: true
    )
  }

  stages {
    /*
    Build image using build config "researchfi-frontend-build".
    After build is complete, OpenShift's image change trigger automatically updates devel deployment.
    Wait until devel pod is ready. 
    */
    stage('Build image') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              // Get build config
              def buildConfig = openshift.selector("bc", "researchfi-frontend-build")
              // Start build and display logs
              buildConfig.startBuild().logs("-f")

              // New image gets automatically tagged "latest", it is defined in the OpenShift build config.
              // Tag image also using short Git commit hash.
              // openshift.tag("researchfi-frontend-devel:latest", "researchfi-frontend-devel:${GIT_COMMIT_SHORT}")
            }
          }
        }
      }
    }

    /*
    Wait until devel deployment is ready.
    At this point the devel environment should be deploying, triggered by a new image from previous step. 
    */
    stage('Wait devel deployment') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              sleep 30
              timeout(5) { 
                openshift.selector("dc", "researchfi-frontend-devel-deployment").related('pods').untilEach(1) {
                  return (it.object().status.phase == "Running")
                }
              }
            }
          }
        }
      }
    }

    /*
    Deploy to production.
    Confirm deployment by prompting user.
    Production deployment is triggered by tagging the devel "latest" as production "latest".
    Also tag the production "latest" with Git commit hash.
    */
    stage('Deploy to production') {
      steps {
        timeout(time: 12, unit: 'HOURS') {
          input message: "Deploy to production?", ok: "Deploy"
        }
        script {
          openshift.withCluster() {
            openshift.withProject() {
              openshift.tag("researchfi-frontend-devel:latest", "researchfi-frontend-production:latest")
              // openshift.tag("researchfi-frontend-production:latest", "researchfi-frontend-production:${GIT_COMMIT_SHORT}")
            }
          }
        }
      }
    }
  }
}