# This file is part of the research.fi service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: researchfi-frontend
    template: researchfi-frontend
  name: researchfi-frontend
objects:
  # Service (development)
  - apiVersion: v1
    kind: Service
    metadata:
      name: researchfi-frontend-devel-service
      labels:
        app: researchfi-frontend
      annotations:
        description: Research.fi frontend service for development
    spec:
      ports:
        - name: frontend
          port: 8080
          targetPort: 8080
      selector:
        depcfg: frontend-devel

  # Service (production)
  - apiVersion: v1
    kind: Service
    metadata:
      name: researchfi-frontend-production-service
      labels:
        app: researchfi-frontend
      annotations:
        description: Research.fi frontend service for production
    spec:
      ports:
        - name: frontend
          port: 8081
          targetPort: 8081
      selector:
        depcfg: frontend-production

  # ImageStream (development)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: researchfi-frontend-devel
      labels:
        app: researchfi-frontend

  # ImageStream (production)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: researchfi-frontend-production
      labels:
        app: researchfi-frontend

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: researchfi-frontend-build
      labels:
        app: researchfi-frontend
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-frontend.git
          ref: devel
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: openshift/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: researchfi-frontend-devel:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4

  # Jenkins pipeline
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: researchfi-frontend-pipeline
      labels:
        app: researchfi-frontend
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-frontend.git
          ref: devel
        contextDir: .
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: openshift/Jenkinsfile

  # Deployment config (development)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: researchfi-frontend-devel-deployment
      labels:
        app: researchfi-frontend
    spec:
      selector:
        app: researchfi-frontend
        depcfg: frontend-devel
      template:
        metadata:
          labels:
            app: researchfi-frontend
            depcfg: frontend-devel
        spec:
          containers:
            - name: frontend-devel
              image: researchfi/researchfi-frontend-devel
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: config-volume-fi
                  mountPath: /dist/browser/assets/config
                - name: config-volume-sv
                  mountPath: /dist/browser/sv/assets/config
                - name: config-volume-en
                  mountPath: /dist/browser/en/assets/config
          volumes:
            - name: config-volume-fi
              configMap:
                name: frontend-config-devel
                items:
                  - key: configfile
                    path: config.json
            - name: config-volume-sv
              configMap:
                name: frontend-config-devel
                items:
                  - key: configfile
                    path: config.json
            - name: config-volume-en
              configMap:
                name: frontend-config-devel
                items:
                  - key: configfile
                    path: config.json
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - frontend-devel
            from:
              kind: ImageStreamTag
              name: researchfi-frontend-devel:latest
      strategy:
        type: Rolling

  # Deployment config (production)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: researchfi-frontend-production-deployment
      labels:
        app: researchfi-frontend
    spec:
      selector:
        app: researchfi-frontend
        depcfg: frontend-production
      template:
        metadata:
          labels:
            app: researchfi-frontend
            depcfg: frontend-production
        spec:
          containers:
            - name: frontend-production
              image: researchfi/researchfi-frontend-production
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: config-volume-fi
                  mountPath: /dist/browser/assets/config
                - name: config-volume-sv
                  mountPath: /dist/browser/sv/assets/config
                - name: config-volume-en
                  mountPath: /dist/browser/en/assets/config
          volumes:
            - name: config-volume-fi
              configMap:
                name: frontend-config-production
                items:
                  - key: configfile
                    path: config.json
            - name: config-volume-sv
              configMap:
                name: frontend-config-production
                items:
                  - key: configfile
                    path: config.json
            - name: config-volume-en
              configMap:
                name: frontend-config-production
                items:
                  - key: configfile
                    path: config.json
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - frontend-production
            from:
              kind: ImageStreamTag
              name: researchfi-frontend-production:latest
      strategy:
        type: Rolling
