# This file is part of the research.fi service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: researchfi-frontend-production
    template: researchfi-frontend-production
  name: researchfi-frontend-production
objects:

# Service (staging)
- apiVersion: v1
  kind: Service
  metadata:
    name: researchfi-frontend-production-staging-service
    labels:
      app: researchfi-frontend-production
    annotations:
      description: Research.fi frontend service for production staging
  spec:
    ports:
      - name: frontend
        port: 8080
        targetPort: 8080
    selector:
      depcfg: frontend-production-staging

# Service (production)
- apiVersion: v1
  kind: Service
  metadata:
    name: researchfi-frontend-production-service
    labels:
      app: researchfi-frontend-production
    annotations:
      description: Research.fi frontend service for production
  spec:
    ports:
      - name: frontend
        port: 8080
        targetPort: 8080
    selector:
      depcfg: frontend-production

# ImageStream (staging)
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: researchfi-frontend-production-staging
    labels:
      app: researchfi-frontend-production

# ImageStream (production)
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: researchfi-frontend-production
    labels:
      app: researchfi-frontend-production

# BuildConfig using Docker build strategy
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: researchfi-frontend-production-build
    labels:
      app: researchfi-frontend-production
  spec:
    source:
      git:
        uri: https://github.com/CSCfi/research-fi-frontend.git
        ref: production
      contextDir: .
    strategy:
      dockerStrategy:
        dockerfilePath: openshift/Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: researchfi-frontend-production-staging:latest
    successfulBuildsHistoryLimit: 20 
    failedBuildsHistoryLimit: 20

# Jenkins pipeline
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: researchfi-frontend-pipeline-production
    labels:
      app: researchfi-frontend-production
  spec:
    source:
      git:
        uri: https://github.com/CSCfi/research-fi-frontend.git
        ref: production
      contextDir: .
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/Jenkinsfile-production

# Deployment config (staging)
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: researchfi-frontend-deployment-production-staging
    labels:
      app: researchfi-frontend-production
  spec:
    selector:
      app: researchfi-frontend-production
      depcfg: frontend-production-staging
    template:
      metadata:
        labels:
          app: researchfi-frontend-production
          depcfg: frontend-production-staging
      spec:
        containers:
          - name: frontend-production-staging
            image: researchfi/researchfi-frontend-production-staging:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
            volumeMounts:
            - name: config-volume-fi
              mountPath: /dist/browser/assets/config
            - name: config-volume-sv
              mountPath: /dist/browser/sv/assets/config
            - name: config-volume-en
              mountPath: /dist/browser/en/assets/config
        volumes:
          - name: config-volume-fi
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
          - name: config-volume-sv
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
          - name: config-volume-en
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
    replicas: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - frontend-production-staging
        from:
          kind: ImageStreamTag
          name: researchfi-frontend-production-staging:latest
    strategy:
      type: Rolling

# Deployment config (production)
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: researchfi-frontend-deployment-production
    labels:
      app: researchfi-frontend-production
  spec:
    selector:
      app: researchfi-frontend-production
      depcfg: frontend-production
    template:
      metadata:
        labels:
          app: researchfi-frontend-production
          depcfg: frontend-production
      spec:
        containers:
          - name: frontend-production
            image: researchfi/researchfi-frontend-production
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
            volumeMounts:
            - name: config-volume-fi
              mountPath: /dist/browser/assets/config
            - name: config-volume-sv
              mountPath: /dist/browser/sv/assets/config
            - name: config-volume-en
              mountPath: /dist/browser/en/assets/config
        volumes:
          - name: config-volume-fi
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
          - name: config-volume-sv
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
          - name: config-volume-en
            configMap:
              name: frontend-config-production
              items:
              - key: configfile
                path: config.json
    replicas: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - frontend-production
        from:
          kind: ImageStreamTag
          name: researchfi-frontend-production:latest
    strategy:
      type: Rolling