# This file is part of the research.fi API service
#
# Copyright 2026 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

# Use non-root version of nginx
FROM image-registry.openshift-image-registry.svc:5000/researchfi-qa/nginx-unprivileged:latest
ENV TZ=Europe/Helsinki
COPY service_break_page/nginx.conf /etc/nginx/
COPY service_break_page/html /usr/share/nginx/html
EXPOSE 8080