# This file is part of the research.fi service
#
# Copyright 2025 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: nginx-service-break-page
    template: nginx-service-break-page
  name: nginx-service-break-page
  annotations:
    description: Nginx service break page
    iconClass: icon-nginx
objects:

  # Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service-break-page
      labels:
        app: nginx-service-break-page
      annotations:
        description: Nginx service break page
    spec:
      ports:
        - name: nginx-service-break-page
          port: 8080
          targetPort: 8080
      selector:
        app: nginx-service-break-page

  # ImageStream
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: nginx-service-break-page
      labels:
        app: nginx-service-break-page

  # BuildConfig using Docker build strategy
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: nginx-service-break-page
      labels:
        app: nginx-service-break-page
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-frontend.git
          ref: devel
        contextDir: .
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: service_break_page/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: nginx-service-break-page:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  # Deployment config
  - apiVersion: apps/v1
    kind: DeploymentConfig
    metadata:
      name: nginx-service-break-page
      labels:
        app: nginx-service-break-page
    spec:
      selector:
        matchLabels:
          app: nginx-service-break-page
      template:
        metadata:
          labels:
            app: nginx-service-break-page
        spec:
          containers:
            - name: nginx-service-break-page
              image: image-registry.openshift-image-registry.svc:5000/researchfi-production/nginx-service-break-page
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nginx-service-break-page
            from:
              kind: ImageStreamTag
              name: nginx-service-break-page:latest
      strategy:
        type: Rolling
